### ISSUE TITLE
How to add breakpoints to every method?

### ISSUE THREAD

**Issue by Tony20221** [timi992000/VSBreakpointExtension#13]
How to add breakpoints to every method? I can't find any documentation.

**Comment by timi992000** [comment]
Hi Tony,

you can Open a Window via Tools - VsBreakpointextension.

Then you have a toolwindow with Options.

**Comment by Tony20221** [comment]
Thanks. I suggest you add this to the description in the extension in the VS Marketplace. The first question a user will wonder is .. how to use it.

**Comment by timi992000** [comment]
> Thanks. I suggest you add this to the description in the extension in the VS Marketplace. The first question a user will wonder is .. how to use it.

Done, Feel free to check it out and let me know what you think

**Comment by Tony20221** [comment]
Looks great.
